const $=id=>document.getElementById(id);const on=(id,event,fn)=>{const el=$(id);if(el)el.addEventListener(event,fn);return el};
const results=$("results"),emptyState=$("empty-state"),databaseState=$("database-state"),searchInput=$("search-input"),searchForm=$("search-form"),countryFilter=$("country-filter"),countryGrid=$("country-grid"),statIps=$("stat-ips"),statCountries=$("stat-countries"),statCities=$("stat-cities"),modal=$("submit-modal"),formMessage=$("form-message"),submitForm=$("submit-form"),submitButton=$("submit-button"),geolocateButton=$("geolocate-button"),ipInput=$("ip-input"),editedIpInput=$("edited-ip-input"),geoStep=$("geo-step"),ipStep=$("ip-step");
const API="/api";let currentPreview=null;
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));const flags={CA:"🇨🇦",US:"🇺🇸",GB:"🇬🇧",DE:"🇩🇪",FR:"🇫🇷",NL:"🇳🇱",JP:"🇯🇵",AU:"🇦🇺"};const flagFor=c=>flags[c]||"🌐";
const setField=(id,value)=>{const el=$(id);if(el)el.value=value??""};const getField=id=>$(id)?.value?.trim()||"";
async function getJson(url,options={}){const r=await fetch(url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
function setMessage(text,error=false){if(!formMessage)return;formMessage.textContent=text;formMessage.classList.remove("hidden");formMessage.style.color=error?"#ff9e9e":"";formMessage.style.background=error?"rgba(255,110,110,.08)":""}
function loadFormGeo(geo,ip){if(!geo||typeof geo!=="object")throw new Error("Geolocation service returned an invalid response.");setField("country-name-input",geo.country_name);setField("region-input",geo.region_name);setField("city-input",geo.city_name);setField("organization-input",geo.organization);setField("proxy-input",geo.proxy_status||"Not detected");setField("edited-ip-input",ip)}
function readEdited(){return{ip:getField("edited-ip-input"),country_code:currentPreview?.geo?.country_code||"",country_name:getField("country-name-input"),region_name:getField("region-input"),city_name:getField("city-input"),organization:getField("organization-input"),usage_type:getField("proxy-input")}}
async function loadStats(){try{const d=await getJson(`${API}/stats`);if(statIps)statIps.textContent=Number(d.ips||0).toLocaleString();if(statCountries)statCountries.textContent=Number(d.countries||0).toLocaleString();if(statCities)statCities.textContent=Number(d.cities||0).toLocaleString();databaseState?.classList.add("hidden")}catch(e){if(statIps)statIps.textContent=ifMissing(statIps,"—");if(statCountries)statCountries.textContent="—";if(statCities)statCities.textContent="—";if(databaseState){databaseState.textContent=`Database is unavailable: ${e.message}`;databaseState.classList.remove("hidden")}}}
const ifMissing=(el,v)=>el?.textContent||v;
function renderResults(items){if(!results)return;results.innerHTML=items.map(e=>`<article class="ip-card"><div class="ip-top"><span class="ip-address">${esc(e.ip)}</span><span class="ip-version">IPv${esc(e.ip_version||(e.ip.includes(":")?6:4))}</span></div><div class="ip-meta"><div class="meta-item"><span>Location</span><strong>${esc(e.city_name||"Unknown")}${e.region_name?`, ${esc(e.region_name)}`:""}</strong></div><div class="meta-item"><span>Organization</span><strong>${esc(e.organization||e.isp||"Unknown")}</strong></div><div class="meta-item"><span>Country</span><strong>${flagFor(e.country_code)} ${esc(e.country_name||e.country_code||"Unknown")}</strong></div><div class="meta-item"><span>Usage</span><strong>${esc(e.usage_type||"Unknown")}</strong></div></div><div class="card-footer"><span class="country-tag">${esc(e.city_name||"Unknown")}</span><button class="copy-ip" data-copy="${esc(e.ip)}">Copy IP</button></div></article>`).join("");if(emptyState)emptyState.classList.toggle("hidden",items.length!==0);results.classList.toggle("hidden",items.length===0);results.querySelectorAll("[data-copy]").forEach(b=>b.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);b.textContent="Copied!";setTimeout(()=>b.textContent="Copy IP",1200)}catch{b.textContent=b.dataset.copy}}))}
function renderCountryGrid(items){if(!countryGrid)return;const g={};items.forEach(e=>{if(!e.country_code)return;(g[e.country_code]??={name:e.country_name||e.country_code,count:0}).count++});countryGrid.innerHTML=Object.entries(g).sort((a,b)=>b[1].count-a[1].count).map(([c,d])=>`<button class="country-card" data-country="${esc(c)}"><div class="country-name"><span>${flagFor(c)}</span>${esc(d.name)}</div><div class="country-count">${d.count} current ${d.count===1?"entry":"entries"}</div></button>`).join("");countryGrid.querySelectorAll("[data-country]").forEach(b=>b.addEventListener("click",()=>{if(countryFilter)countryFilter.value=b.dataset.country;if(searchInput)searchInput.value="";loadResults();$("directory")?.scrollIntoView({behavior:"smooth"})}))}
async function loadResults(){const p=new URLSearchParams({limit:"100"});if(searchInput?.value.trim())p.set("q",searchInput.value.trim());if(countryFilter?.value)p.set("country",countryFilter.value);try{const d=await getJson(`${API}/search?${p}`);renderResults(d.results||[]);renderCountryGrid(d.results||[]);databaseState?.classList.add("hidden")}catch(e){renderResults([]);if(databaseState){databaseState.textContent=`Search is unavailable: ${e.message}`;databaseState.classList.remove("hidden")}}}
function openModal(){if(!modal)return;modal.classList.remove("hidden");modal.setAttribute("aria-hidden","false");ipStep?.classList.remove("hidden");geoStep?.classList.add("hidden");formMessage?.classList.add("hidden");currentPreview=null;if(geolocateButton){geolocateButton.disabled=false;geolocateButton.textContent="Geolocate IP"}ipInput?.focus();document.body.style.overflow="hidden"}
function closeModal(){if(!modal)return;modal.classList.add("hidden");modal.setAttribute("aria-hidden","true");document.body.style.overflow=""}
on("search-form","submit",e=>{e.preventDefault();loadResults();$("directory")?.scrollIntoView({behavior:"smooth"})});on("search-input","input",()=>{clearTimeout(window.__pm);window.__pm=setTimeout(loadResults,180)});on("country-filter","change",loadResults);on("clear-search","click",()=>{if(searchInput)searchInput.value="";if(countryFilter)countryFilter.value="";loadResults()});document.addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();searchInput?.focus()}if(e.key==="Escape")closeModal()});on("open-submit-top","click",openModal);on("open-submit-main","click",openModal);on("close-submit","click",closeModal);modal?.addEventListener("click",e=>{if(e.target===modal)closeModal()});
on("use-my-ip","click",async()=>{try{const d=await getJson(`${API}/my-ip`);if(!d.ip)throw new Error("Cloudflare did not provide your public IP.");if(ipInput)ipInput.value=d.ip}catch(e){setMessage(e.message,true)}});on("back-to-ip","click",()=>{geoStep?.classList.add("hidden");ipStep?.classList.remove("hidden");formMessage?.classList.add("hidden");if(ipInput)ipInput.value=getField("edited-ip-input")||ipInput.value});
on("geolocate-button","click",async()=>{const ip=ipInput?.value.trim()||"";if(!ip)return setMessage("Enter a public IP address first.",true);if(!geolocateButton)return;geolocateButton.disabled=true;geolocateButton.textContent="Geolocating…";formMessage?.classList.add("hidden");try{const d=await getJson(`${API}/preview`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ip})});if(!d.ip||!d.geo)throw new Error("Geolocation service returned no location data.");currentPreview={ip:d.ip,geo:d.geo};loadFormGeo(d.geo,d.ip);ipStep?.classList.add("hidden");geoStep?.classList.remove("hidden");setMessage("Geolocation found. Review the information, or change the IP before submitting.");if(submitButton){submitButton.disabled=false;submitButton.textContent="Verify ping + add"}}catch(e){setMessage(e.message,true);geolocateButton.disabled=false;geolocateButton.textContent="Geolocate IP"}});
submitForm?.addEventListener("submit",async e=>{e.preventDefault();if(!currentPreview)return setMessage("Geolocate the IP first.",true);const edited=readEdited();if(!edited.ip)return setMessage("Enter an IP address.",true);if(!edited.country_code||!edited.country_name||!edited.city_name)return setMessage("Country and city are required.",true);if(submitButton){submitButton.disabled=true;submitButton.textContent="Pinging + adding…"}setMessage("Running the ICMP reachability check. The IP will only be added if it responds.");try{const d=await getJson(`${API}/submit`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(edited)});setMessage(`Added ${d.entry.ip} — ${d.entry.city_name}, ${d.entry.region_name}, ${d.entry.country_name}. Average ping: ${d.ping.avgMs??"—"} ms.`);if(submitButton)submitButton.textContent="Added!";await Promise.all([loadStats(),loadResults()])}catch(e){setMessage(e.message,true);if(submitButton){submitButton.disabled=false;submitButton.textContent="Verify ping + add"}}});
(async()=>{await loadStats();await loadResults()})();
