const results=document.getElementById("results"),emptyState=document.getElementById("empty-state"),databaseState=document.getElementById("database-state"),searchInput=document.getElementById("search-input"),searchForm=document.getElementById("search-form"),countryFilter=document.getElementById("country-filter"),countryGrid=document.getElementById("country-grid"),statIps=document.getElementById("stat-ips"),statCountries=document.getElementById("stat-countries"),statCities=document.getElementById("stat-cities"),modal=document.getElementById("submit-modal"),formMessage=document.getElementById("form-message"),submitForm=document.getElementById("submit-form"),submitButton=document.getElementById("submit-button"),geolocateButton=document.getElementById("geolocate-button"),ipInput=document.getElementById("ip-input"),editedIpInput=document.getElementById("edited-ip-input"),geoStep=document.getElementById("geo-step"),ipStep=document.getElementById("ip-step");
const API="/api";let currentPreview=null;
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));const flags={CA:"🇨🇦",US:"🇺🇸",GB:"🇬🇧",DE:"🇩🇪",FR:"🇫🇷",NL:"🇳🇱",JP:"🇯🇵",AU:"🇦🇺"};const flagFor=c=>flags[c]||"🌐";
const field=id=>document.getElementById(id);const setField=(id,value)=>{const el=field(id);if(el)el.value=value??"";};const getField=id=>field(id)?.value?.trim()||"";
async function getJson(url,options={}){const r=await fetch(url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
function setMessage(text,error=false){if(!formMessage)return;formMessage.textContent=text;formMessage.classList.remove("hidden");formMessage.style.color=error?"#ff9e9e":"";formMessage.style.background=error?"rgba(255,110,110,.08)":""}
function loadFormGeo(geo,ip){if(!geo||typeof geo!=="object")throw new Error("Geolocation service returned an invalid response.");setField("country-name-input",geo.country_name);setField("region-input",geo.region_name);setField("city-input",geo.city_name);setField("organization-input",geo.organization);setField("proxy-input",geo.proxy_status||"Not detected");setField("edited-ip-input",ip);if(!editedIpInput&&!field("edited-ip-input"))throw new Error("The editable IP field is missing from the page.")}
function readEdited(){return{ip:getField("edited-ip-input"),country_code:currentPreview?.geo?.country_code||"",country_name:getField("country-name-input"),region_name:getField("region-input"),city_name:getField("city-input"),organization:getField("organization-input"),usage_type:getField("proxy-input")}}
async function loadStats(){try{const d=await getJson(`${API}/stats`);statIps.textContent=Number(d.ips||0).toLocaleString();statCountries.textContent=Number(d.countries||0).toLocaleString();statCities.textContent=Number(d.cities||0).toLocaleString();databaseState.classList.add("hidden")}catch(e){statIps.textContent=statCountries.textContent=statCities.textContent="—";databaseState.textContent=`Database is unavailable: ${e.message}`;databaseState.classList.remove("hidden")}}
function renderResults(items){results.innerHTML=items.map(e=>`<article class="ip-card"><div class="ip-top"><span class="ip-address">${esc(e.ip)}</span><span class="ip-version">IPv${esc(e.ip_version||(e.ip.includes(":")?6:4))}</span></div><div class="ip-meta"><div class="meta-item"><span>Location</span><strong>${esc(e.city_name||"Unknown")}${e.region_name?`, ${esc(e.region_name)}`:""}</strong></div><div class="meta-item"><span>Organization</span><strong>${esc(e.organization||e.isp||"Unknown")}</strong></div><div class="meta-item"><span>Country</span><strong>${flagFor(e.country_code)} ${esc(e.country_name||e.country_code||"Unknown")}</strong></div><div class="meta-item"><span>Usage</span><strong>${esc(e.usage_type||"Unknown")}</strong></div></div><div class="card-footer"><span class="country-tag">${esc(e.city_name||"Unknown")}</span><button class="copy-ip" data-copy="${esc(e.ip)}">Copy IP</button></div></article>`).join("");emptyState.classList.toggle("hidden",items.length!==0);results.classList.toggle("hidden",items.length===0);results.querySelectorAll("[data-copy]").forEach(b=>b.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);b.textContent="Copied!";setTimeout(()=>b.textContent="Copy IP",1200)}catch{b.textContent=b.dataset.copy}}))}
function renderCountryGrid(items){const g={};items.forEach(e=>{if(!e.country_code)return;(g[e.country_code]??={name:e.country_name||e.country_code,count:0}).count++});countryGrid.innerHTML=Object.entries(g).sort((a,b)=>b[1].count-a[1].count).map(([c,d])=>`<button class="country-card" data-country="${esc(c)}"><div class="country-name"><span>${flagFor(c)}</span>${esc(d.name)}</div><div class="country-count">${d.count} current ${d.count===1?"entry":"entries"}</div></button>`).join("");countryGrid.querySelectorAll("[data-country]").forEach(b=>b.addEventListener("click",()=>{countryFilter.value=b.dataset.country;searchInput.value="";loadResults();document.getElementById("directory").scrollIntoView({behavior:"smooth"})}))}
async function loadResults(){const p=new URLSearchParams({limit:"100"});if(searchInput.value.trim())p.set("q",searchInput.value.trim());if(countryFilter.value)p.set("country",countryFilter.value);try{const d=await getJson(`${API}/search?${p}`);renderResults(d.results||[]);renderCountryGrid(d.results||[]);databaseState.classList.add("hidden")}catch(e){renderResults([]);databaseState.textContent=`Search is unavailable: ${e.message}`;databaseState.classList.remove("hidden")}}
function openModal(){modal.classList.remove("hidden");modal.setAttribute("aria-hidden","false");ipStep.classList.remove("hidden");geoStep.classList.add("hidden");formMessage.classList.add("hidden");currentPreview=null;geolocateButton.disabled=false;geolocateButton.textContent="Geolocate IP";ipInput.focus();document.body.style.overflow="hidden"}function closeModal(){modal.classList.add("hidden");modal.setAttribute("aria-hidden","true");document.body.style.overflow=""}
searchForm.addEventListener("submit",e=>{e.preventDefault();loadResults();document.getElementById("directory").scrollIntoView({behavior:"smooth")});searchInput.addEventListener("input",()=>{clearTimeout(window.__pm);window.__pm=setTimeout(loadResults,180)});countryFilter.addEventListener("change",loadResults);document.getElementById("clear-search").addEventListener("click",()=>{searchInput.value="";countryFilter.value="";loadResults()});document.addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement.tagName!=="INPUT"){e.preventDefault();searchInput.focus()}if(e.key==="Escape")closeModal()});document.getElementById("open-submit-top").addEventListener("click",openModal);document.getElementById("open-submit-main").addEventListener("click",openModal);document.getElementById("close-submit").addEventListener("click",closeModal);modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});
document.getElementById("use-my-ip").addEventListener("click",async()=>{try{const d=await getJson(`${API}/my-ip`);if(!d.ip)throw new Error("Cloudflare did not provide your public IP.");ipInput.value=d.ip}catch(e){setMessage(e.message,true)}});document.getElementById("back-to-ip").addEventListener("click",()=>{geoStep.classList.add("hidden");ipStep.classList.remove("hidden");formMessage.classList.add("hidden");ipInput.value=getField("edited-ip-input")||ipInput.value});
geolocateButton.addEventListener("click",async()=>{const ip=ipInput.value.trim();if(!ip)return setMessage("Enter a public IP address first.",true);geolocateButton.disabled=true;geolocateButton.textContent="Geolocating…";formMessage.classList.add("hidden");try{const d=await getJson(`${API}/preview`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ip})});if(!d.ip||!d.geo)throw new Error("Geolocation service returned no location data.");currentPreview={ip:d.ip,geo:d.geo};loadFormGeo(d.geo,d.ip);ipStep.classList.add("hidden");geoStep.classList.remove("hidden");setMessage("Geolocation found. Review the information, or change the IP before submitting.");submitButton.disabled=false;submitButton.textContent="Verify ping + add"}catch(e){setMessage(e.message,true);geolocateButton.disabled=false;geolocateButton.textContent="Geolocate IP"}});
submitForm.addEventListener("submit",async e=>{e.preventDefault();if(!currentPreview)return setMessage("Geolocate the IP first.",true);const edited=readEdited();if(!edited.ip)return setMessage("Enter an IP address.",true);if(!edited.country_code||!edited.country_name||!edited.city_name)return setMessage("Country and city are required.",true);submitButton.disabled=true;submitButton.textContent="Pinging + adding…";setMessage("Running the ICMP reachability check. The IP will only be added if it responds.");try{const d=await getJson(`${API}/submit`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(edited)});setMessage(`Added ${d.entry.ip} — ${d.entry.city_name}, ${d.entry.region_name}, ${d.entry.country_name}. Average ping: ${d.ping.avgMs??"—"} ms.`);submitButton.textContent="Added!";await Promise.all([loadStats(),loadResults()])}catch(e){setMessage(e.message,true);submitButton.disabled=false;submitButton.textContent="Verify ping + add"}});
(async()=>{await loadStats();await loadResults()})();
