const RATE_LIMIT = new Map();
const RATE_WINDOW_MS = 30000;
const OWNER = "Maneetbal";
const REPO = "globalpingmap";
const BRANCH = "main";
const GH = "https://api.github.com";
let cache = { expires: 0, files: null };

const json = (data, status = 200) => new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" } });
const isIPv4 = ip => /^(25[0-5]|2[0-4]\d|1?\d?\d)(\.(25[0-5]|2[0-4]\d|1?\d?\d)){3}$/.test(ip);
const isIPv6 = ip => ip.includes(":") && /^[0-9a-f:]+$/i.test(ip) && ip.length <= 45;
function publicIp(ip) {
  if (isIPv4(ip)) { const p = ip.split(".").map(Number); const n = (((p[0]*256+p[1])*256+p[2])*256+p[3])>>>0; return ![[0,0xffffff],[0x0a000000,0x0affffff],[0x64400000,0x647fffff],[0x7f000000,0x7fffffff],[0xa9fe0000,0xa9feffff],[0xac100000,0xac1fffff],[0xc0000000,0xc00000ff],[0xc0000200,0xc00002ff],[0xc0a80000,0xc0a8ffff],[0xe0000000,0xffffffff]].some(([a,b])=>n>=a&&n<=b); }
  if (!isIPv6(ip)) return false; const x=ip.toLowerCase(); return x!=="::"&&x!=="::1"&&!/^f[cd]|^fe[89ab]|^ff/i.test(x);
}
function limited(key) { const now=Date.now(), old=RATE_LIMIT.get(key)||0; if(now-old<RATE_WINDOW_MS)return true; RATE_LIMIT.set(key,now); return false; }
async function geolocate(ip) { const r=await fetch(`https://api.ip2location.io/?ip=${encodeURIComponent(ip)}&format=json`,{cf:{cacheTtl:3600,cacheEverything:true}}); if(!r.ok)throw new Error(`IP2Location returned HTTP ${r.status}`); const d=await r.json(); if(!d?.country_code||!d?.city_name)throw new Error("IP2Location could not determine a location"); return d; }
async function ping(ip) { const r=await fetch("https://api.globalping.io/v1/measurements",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({target:ip,type:"ping",locations:[{limit:1}],measurementOptions:{packets:3,ipVersion:isIPv6(ip)?6:4}})}); if(!r.ok)throw new Error(`Globalping create failed (${r.status})`); const c=await r.json(); if(!c?.id)throw new Error("Globalping did not return a measurement ID"); for(let i=0;i<8;i++){if(i)await new Promise(x=>setTimeout(x,900)); const q=await fetch(`https://api.globalping.io/v1/measurements/${encodeURIComponent(c.id)}`); if(!q.ok)continue; const d=await q.json(); if(d.status==="in-progress")continue; const s=(d.results||[]).map(x=>x?.result?.stats).filter(Boolean).find(x=>Number(x.rcv||0)>0||Number(x.loss)<100); return s?{reachable:true,loss:Number(s.loss??0),avgMs:Number(s.avg??0),measurementId:c.id}:{reachable:false,loss:100,avgMs:null,measurementId:c.id}; } throw new Error("Globalping measurement timed out"); }
function ghHeaders(env) { if(!env.GITHUB_TOKEN)throw new Error("GitHub database is not connected yet. Add the GITHUB_TOKEN Worker secret."); return {Authorization:`Bearer ${env.GITHUB_TOKEN}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"globalpingmap-worker"}; }
async function gh(env,path,options={}) { const r=await fetch(`${GH}${path}`,{...options,headers:{...ghHeaders(env),...(options.headers||{})}}); if(!r.ok){const t=await r.text();throw new Error(`GitHub API ${r.status}: ${t.slice(0,200)}`);} return r; }
function decode(v){const b=atob(v.replace(/\n/g,""));return new TextDecoder().decode(Uint8Array.from(b,c=>c.charCodeAt(0)));}
function encode(v){const a=new TextEncoder().encode(v);let b="";for(let i=0;i<a.length;i+=32768)b+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(b);}
async function file(env,path){const r=await gh(env,`/repos/${OWNER}/${REPO}/contents/${path}?ref=${BRANCH}`);const d=await r.json();if(d.type!=="file")throw new Error(`${path} is not a file`);return{sha:d.sha,content:decode(d.content)};}
async function ipFiles(env,force=false){if(!force&&cache.files&&cache.expires>Date.now())return cache.files;const r=await gh(env,`/repos/${OWNER}/${REPO}/git/trees/${BRANCH}?recursive=1`);const d=await r.json();if(d.truncated)throw new Error("GitHub data tree is too large; add a generated data index.");cache={expires:Date.now()+60000,files:(d.tree||[]).filter(x=>x.type==="blob"&&x.path.startsWith("data/countries/")&&x.path.endsWith("/ips.json")).map(x=>x.path)};return cache.files;}
async function allEntries(env){const out=[];for(const p of await ipFiles(env)){try{const d=JSON.parse((await file(env,p)).content);for(const e of(Array.isArray(d)?d:d.entries||[]))out.push({...e,_path:p});}catch(_){} }return out;}
function part(v,f="Unknown"){const x=String(v||f).trim().replace(/[\\/:*?"<>|#%]/g,"-").replace(/\s+/g," ").replace(/^\.+|\.+$/g,"").slice(0,120);return x||f;}
function cityPath(e){return `data/countries/${part(e.country_code.toUpperCase(),"XX")}/regions/${part(e.region_name)}/cities/${part(e.city_name)}/ips.json`;}
function geo(d){return{country_code:d.country_code||"",country_name:d.country_name||"",region_name:d.region_name||"",city_name:d.city_name||"",latitude:d.latitude??null,longitude:d.longitude??null,zip_code:d.zip_code||"",time_zone:d.time_zone||"",asn:d.asn?String(d.asn):"",as_name:d.as||"",isp:d.isp||d.as||"",domain:d.domain||"",usage_type:d.usage_type||"",is_proxy:d.is_proxy?1:0};}
async function preview(request){const c=request.headers.get("CF-Connecting-IP")||"unknown";if(limited(`preview:${c}`))return json({error:"Please wait before requesting another geolocation preview."},429);let b;try{b=await request.json();}catch{return json({error:"Invalid JSON body."},400);}const ip=String(b?.ip||"").trim().toLowerCase();if(!publicIp(ip))return json({error:"Only public IPv4/IPv6 addresses can be previewed."},400);return json({ok:true,ip,geo:geo(await geolocate(ip))});}
async function submit(request,env){const c=request.headers.get("CF-Connecting-IP")||"unknown";if(limited(`submit:${c}`))return json({error:"Please wait before submitting another IP."},429);let b;try{b=await request.json();}catch{return json({error:"Invalid JSON body."},400);}const ip=String(b?.ip||"").trim().toLowerCase();if(!publicIp(ip))return json({error:"Only public IPv4/IPv6 addresses can be submitted."},400);const clean=v=>String(v??"").trim().slice(0,300);const e={ip,ip_version:isIPv6(ip)?6:4,country_code:clean(b.country_code).toUpperCase().slice(0,2),country_name:clean(b.country_name),region_name:clean(b.region_name),city_name:clean(b.city_name),latitude:Number.isFinite(Number(b.latitude))?Number(b.latitude):null,longitude:Number.isFinite(Number(b.longitude))?Number(b.longitude):null,zip_code:clean(b.zip_code),time_zone:clean(b.time_zone),asn:clean(b.asn).replace(/^AS/i,"").slice(0,20),as_name:clean(b.as_name),isp:clean(b.isp),domain:clean(b.domain),usage_type:clean(b.usage_type),is_proxy:!!b.is_proxy,is_reachable:true,ping_avg_ms:null,ping_loss:null,ping_checked_at:null,submitted_at:new Date().toISOString(),source:"community"};if(!e.country_code||!e.country_name||!e.city_name)return json({error:"Country and city are required."},400);if((await allEntries(env)).some(x=>String(x.ip).toLowerCase()===ip))return json({error:"That IP is already in PingMap."},409);const p=await ping(ip);if(!p.reachable)return json({error:"The IP did not answer the ICMP reachability check, so it was not added.",ping:p},422);e.ping_avg_ms=p.avgMs;e.ping_loss=p.loss;e.ping_checked_at=new Date().toISOString();const path=cityPath(e);let value={country_code:e.country_code,country_name:e.country_name,region:e.region_name,city:e.city_name,entries:[]},sha;try{const f=await file(env,path);sha=f.sha;const d=JSON.parse(f.content);value=Array.isArray(d)?{...value,entries:d}:d;}catch(err){if(!String(err.message).includes("GitHub API 404"))throw err;}if(!Array.isArray(value.entries))value.entries=[];if(value.entries.some(x=>String(x.ip).toLowerCase()===ip))return json({error:"That IP is already in this city."},409);value.entries.push(e);value.updated_at=new Date().toISOString();const r=await gh(env,`/repos/${OWNER}/${REPO}/contents/${path}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({message:`Add ${ip} to ${e.city_name} IP directory`,content:encode(JSON.stringify(value,null,2)+"\n"),branch:BRANCH,...(sha?{sha}: {})})});const d=await r.json();cache.expires=0;return json({ok:true,entry:e,ping:p,path,commit:d.commit?.sha||null});}
async function search(request,env){const u=new URL(request.url),q=(u.searchParams.get("q")||"").trim().toLowerCase(),country=(u.searchParams.get("country")||"").trim().toUpperCase(),limit=Math.min(Math.max(Number(u.searchParams.get("limit")||100),1),100);let r=await allEntries(env);if(q)r=r.filter(e=>[e.ip,e.country_name,e.country_code,e.region_name,e.city_name,e.isp,e.as_name,e.asn,e.domain].some(v=>String(v??"").toLowerCase().includes(q)));if(country)r=r.filter(e=>String(e.country_code||"").toUpperCase()===country);r.sort((a,b)=>String(b.submitted_at||"").localeCompare(String(a.submitted_at||"")));return json({results:r.slice(0,limit),count:Math.min(r.length,limit)});}
async function countries(env){const m=new Map();for(const e of await allEntries(env)){const c=String(e.country_code||"").toUpperCase();if(!c)continue;const x=m.get(c)||{country_code:c,country_name:e.country_name||c,entries:0};x.entries++;m.set(c,x);}return json({results:[...m.values()].sort((a,b)=>a.country_name.localeCompare(b.country_name))});}
async function stats(env){const e=await allEntries(env);return json({ips:e.length,countries:new Set(e.map(x=>x.country_code).filter(Boolean)).size,cities:new Set(e.map(x=>`${x.country_code}:${x.region_name}:${x.city_name}`)).size});}
async function api(request,env){const u=new URL(request.url);try{if(u.pathname==="/api/health"&&request.method==="GET")return json({ok:true,database:"GitHub JSON files",geolocation:"IP2Location.io",reachability:"Globalping"});if(u.pathname==="/api/my-ip"&&request.method==="GET")return json({ip:request.headers.get("CF-Connecting-IP")||null});if(u.pathname==="/api/preview"&&request.method==="POST")return preview(request);if(u.pathname==="/api/search"&&request.method==="GET")return search(request,env);if(u.pathname==="/api/countries"&&request.method==="GET")return countries(env);if(u.pathname==="/api/stats"&&request.method==="GET")return stats(env);if(u.pathname==="/api/submit"&&request.method==="POST")return submit(request,env);return json({error:"Not found"},404);}catch(err){console.error(err);return json({error:err instanceof Error?err.message:"Unexpected server error"},503);}}
export default{async fetch(request,env){return new URL(request.url).pathname.startsWith("/api/")?api(request,env):env.ASSETS.fetch(request);}};
